"""Entity Definitions."""

ENTITY_DEFINITIONS = {
    "sensor": {
        "anlagenzustand": {
            "register": 34001,
            "type": "text",
            "translation_key": "anlagenzustand",
        },
        "kesselzustand": {
            "register": 34002,
            "type": "text",
            "translation_key": "kesselzustand",
        },
        "aussentemperatur": {
            "register": 31001,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "stunden_im_pelletsbetrieb": {
            "register": 30063,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "stunden_im_heizen": {
            "register": 30064,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "stunden_im_scheitholzbetrieb": {
            "register": 30077,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "tuerkontakt": {
            "discrete_input": 10001,
            "type": "binary_sensor",
            "device_class": "door"
        },
        "stb": {
            "discrete_input": 10002,
            "type": "binary_sensor"
        },
        "notaus": {
            "discrete_input": 10003,
            "type": "binary_sensor"
        },
        "kesselfreigabe": {
            "discrete_input": 10004,
            "type": "binary_sensor"
        },
    },
    "kessel": {
        "kesseltemperatur": {
            "register": 30001,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "abgastemperatur": {
            "register": 30002,
            "unit": "°C",
            "scaling": 1,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "boardtemperatur": {
            "register": 30003,
            "unit": "°C",
            "scaling":2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "verbleibende_heizstunden_bis_zur_asche_entleeren_warnung": {
            "register": 30087,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "saugzug_ansteuerung": {
            "register": 30014,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "saugzugdrehzahl": {
            "register": 30007,
            "unit": "upm",
            "scaling": 1,
            "type": "sensor",
        },
        "sauerstoffregler": {
            "register": 30017,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "restsauerstoffgehalt": {
            "register": 30004,
            "unit": "%",
            "scaling": 10,
            "decimals": 1,
            "type": "sensor",
        },
        "ruecklauffuehler": {
            "register": 30010,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "primaerluft": {
            "register": 30012,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "sekundaerluft": {
            "register": 30013,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "betriebsstunden": {
            "register": 30021,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "stunden_seit_letzter_wartung": {
            "register": 30056,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "betriebsstunden_in_der_feuererhaltung": {
            "register": 30025,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "kessel_solltemperatur": {
            "register": 40001,
            "unit": "°C",
            "scaling": 2,
            "min": 70,
            "max": 90,
            "type": "number",
            "device_class": "temperature",
        },
        "bei_welcher_rl_temperatur_an_der_zirkulationsleitung_soll_die_pumpe_ausschalten": {
            "register": 40601,
            "unit": "°C",
            "scaling": 2,
            "min": 20,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "automatisch_zuenden": {
            "register": 40136,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "fehlerpuffer": {
        f"kessel_fehlerpuffer_{i + 1}": {
            "register": 33001 + i,
            "type": "text",
            "translation_key": "kessel_fehler",
        }
        for i in range(20)
    },
    "boiler01": {
        "boiler_1_temperatur_oben": {
            "register": 31631,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "boiler_1_pumpe_ansteuerung": {
            "register": 31633,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "boiler_1_pumpe_an_aus": {
            "register": 31633,
            "type": "binary_sensor_from_register",
        },
        "boiler_1_gewuenschte_boilertemperatur": {
            "register": 41632,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 100,
            "type": "number",
            "device_class": "temperature",
        },
        "boiler_1_nachladen_wenn_boilertemperatur_unter": {
            "register": 41633,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
            "device_class": "temperature",
        },
        "boiler_1_solltemperatur_externe_vorgabe": {
            "register": 48019,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
            "device_class": "temperature",
        },
        "boiler_1_temperatur_solarreferenz": {
            "register": 31632,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
    },
    "boiler02": {
        "boiler_2_temperatur_oben": {
            "register": 31661,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "boiler_2_pumpe_ansteuerung": {
            "register": 31663,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "boiler_2_pumpe_an_aus": {
            "register": 31663,
            "type": "binary_sensor_from_register",
        },
        "boiler_2_gewuenschte_boilertemperatur": {
            "register": 41662,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 100,
            "type": "number",
            "device_class": "temperature",
        },
        "boiler_2_nachladen_wenn_boilertemperatur_unter": {
            "register": 41663,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
            "device_class": "temperature",
        },
        "boiler_2_solltemperatur_externe_vorgabe": {
            "register": 48020,
            "unit": "°C",
            "scaling": 2,
            "min": 1,
            "max": 90,
            "type": "number",
            "device_class": "temperature",
        },
        "boiler_2_temperatur_solarreferenz": {
            "register": 31662,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
    },
    "diff-regler":{
        "diff-regler_temperatur_der_waermequelle":{
            "register": 30801,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "diff-regler_temperatur_der_waermesenke":{
            "register": 30802,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "diff-regler_drehzahl_der_pumpe": {
            "register": 30803,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
    },
    "hk1": {
        "hk1_vorlauf_isttemperatur": {
            "register": 31031,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk1_vorlauf_solltemperatur": {
            "register": 31032,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk1_raumtemperatur": {
            "register": 31033,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk1_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41036,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
        },
        "hk1_vorlauf_temperatur_externe_vorgabe": {
            "register": 48001,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_pumpe_an_aus": {"coil": 1030, "type": "binary_sensor"},
        "hk1_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41032,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
        },
        "hk1_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41033,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41040,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41034,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41037,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41038,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_frostschutztemperatur": {
            "register": 41039,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41048,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk1_betriebsart": {
            "register": 48047,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk1_freigabe_externe_vorgabe": {
            "register": 48029,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk2": {
        "hk2_vorlauf_isttemperatur": {
            "register": 31061,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk2_vorlauf_solltemperatur": {
            "register": 31062,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk2_raumtemperatur": {
            "register": 31063,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk2_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41066,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_vorlauf_temperatur_externe_vorgabe": {
            "register": 48002,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_pumpe_an_aus": {"coil": 1060, "type": "binary_sensor"},
        "hk2_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41062,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41063,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41070,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41064,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41067,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41068,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_frostschutztemperatur": {
            "register": 41069,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41079,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk2_betriebsart": {
            "register": 48048,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk2_freigabe_externe_vorgabe": {
            "register": 48030,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk3": {
        "hk3_vorlauf_isttemperatur": {
            "register": 31091,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk3_vorlauf_solltemperatur": {
            "register": 31092,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk3_raumtemperatur": {
            "register": 31093,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk3_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41096,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_vorlauf_temperatur_externe_vorgabe": {
            "register": 48003,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_pumpe_an_aus": {"coil": 1090, "type": "binary_sensor"},
        "hk3_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41092,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41093,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41100,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41094,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41097,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41098,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_frostschutztemperatur": {
            "register": 41099,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41106,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk3_betriebsart": {
            "register": 48049,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk3_freigabe_externe_vorgabe": {
            "register": 48031,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk4": {
        "hk4_vorlauf_isttemperatur": {
            "register": 31121,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk4_vorlauf_solltemperatur": {
            "register": 31122,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk4_raumtemperatur": {
            "register": 31123,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk4_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41126,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_vorlauf_temperatur_externe_vorgabe": {
            "register": 48004,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_pumpe_an_aus": {"coil": 1120, "type": "binary_sensor"},
        "hk4_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41122,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41123,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41130,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41124,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41127,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41128,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_frostschutztemperatur": {
            "register": 41129,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41136,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk4_betriebsart": {
            "register": 48050,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk4_freigabe_externe_vorgabe": {
            "register": 48032,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk5": {
        "hk5_vorlauf_isttemperatur": {
            "register": 31151,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk5_vorlauf_solltemperatur": {
            "register": 31152,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk5_raumtemperatur": {
            "register": 31153,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk5_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41156,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_vorlauf_temperatur_externe_vorgabe": {
            "register": 48005,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_pumpe_an_aus": {"coil": 1150, "type": "binary_sensor"},
        "hk5_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41152,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41153,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41160,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41154,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41157,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41158,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_frostschutztemperatur": {
            "register": 41159,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41166,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk5_betriebsart": {
            "register": 48051,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk5_freigabe_externe_vorgabe": {
            "register": 48033,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk6": {
        "hk6_vorlauf_isttemperatur": {
            "register": 31181,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk6_vorlauf_solltemperatur": {
            "register": 31182,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk6_raumtemperatur": {
            "register": 31183,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk6_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41186,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_vorlauf_temperatur_externe_vorgabe": {
            "register": 48006,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_pumpe_an_aus": {"coil": 1180, "type": "binary_sensor"},
        "hk6_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41182,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41183,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41190,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41184,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41187,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41188,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_frostschutztemperatur": {
            "register": 41189,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41196,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk6_betriebsart": {
            "register": 48052,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk6_freigabe_externe_vorgabe": {
            "register": 48034,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk7": {
        "hk7_vorlauf_isttemperatur": {
            "register": 31211,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk7_vorlauf_solltemperatur": {
            "register": 31212,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk7_raumtemperatur": {
            "register": 31213,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk7_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41216,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_vorlauf_temperatur_externe_vorgabe": {
            "register": 48007,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_pumpe_an_aus": {"coil": 1210, "type": "binary_sensor"},
        "hk7_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41212,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41213,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41220,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41214,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41217,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41218,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_frostschutztemperatur": {
            "register": 41219,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41226,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk7_betriebsart": {
            "register": 48053,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk7_freigabe_externe_vorgabe": {
            "register": 48035,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk8": {
        "hk8_vorlauf_isttemperatur": {
            "register": 31241,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk8_vorlauf_solltemperatur": {
            "register": 31242,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk8_raumtemperatur": {
            "register": 31243,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk8_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41246,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_vorlauf_temperatur_externe_vorgabe": {
            "register": 48008,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_pumpe_an_aus": {"coil": 1240, "type": "binary_sensor"},
        "hk8_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41242,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41243,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41250,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41244,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41247,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41248,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_frostschutztemperatur": {
            "register": 41249,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41256,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk8_betriebsart": {
            "register": 48054,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk8_freigabe_externe_vorgabe": {
            "register": 48036,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk9": {
        "hk9_vorlauf_isttemperatur": {
            "register": 31271,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk9_vorlauf_solltemperatur": {
            "register": 31272,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk9_raumtemperatur": {
            "register": 31273,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk9_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41276,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_vorlauf_temperatur_externe_vorgabe": {
            "register": 48009,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_pumpe_an_aus": {"coil": 1270, "type": "binary_sensor"},
        "hk9_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41272,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41273,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41280,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41274,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41277,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41278,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_frostschutztemperatur": {
            "register": 41279,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41286,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk9_betriebsart": {
            "register": 48055,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk9_freigabe_externe_vorgabe": {
            "register": 48037,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk10": {
        "hk10_vorlauf_isttemperatur": {
            "register": 31301,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk10_vorlauf_solltemperatur": {
            "register": 31302,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk10_raumtemperatur": {
            "register": 31303,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk10_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41306,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_vorlauf_temperatur_externe_vorgabe": {
            "register": 48010,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_pumpe_an_aus": {"coil": 1300, "type": "binary_sensor"},
        "hk10_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41302,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41303,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41310,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41304,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41307,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41308,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_frostschutztemperatur": {
            "register": 41309,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41316,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk10_betriebsart": {
            "register": 48056,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk10_freigabe_externe_vorgabe": {
            "register": 48038,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk11": {
        "hk11_vorlauf_isttemperatur": {
            "register": 31331,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk11_vorlauf_solltemperatur": {
            "register": 31332,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk11_raumtemperatur": {
            "register": 31333,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk11_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41336,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_vorlauf_temperatur_externe_vorgabe": {
            "register": 48011,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_pumpe_an_aus": {"coil": 1330, "type": "binary_sensor"},
        "hk11_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41332,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41333,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41340,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41334,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41337,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41338,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_frostschutztemperatur": {
            "register": 41339,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41346,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk11_betriebsart": {
            "register": 48057,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk11_freigabe_externe_vorgabe": {
            "register": 48039,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk12": {
        "hk12_vorlauf_isttemperatur": {
            "register": 31361,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk12_vorlauf_solltemperatur": {
            "register": 31362,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk12_raumtemperatur": {
            "register": 31363,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk12_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41366,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_vorlauf_temperatur_externe_vorgabe": {
            "register": 48012,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_pumpe_an_aus": {"coil": 1360, "type": "binary_sensor"},
        "hk12_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41362,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41363,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41370,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41364,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41367,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41368,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_frostschutztemperatur": {
            "register": 41369,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41376,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk12_betriebsart": {
            "register": 48058,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk12_freigabe_externe_vorgabe": {
            "register": 48040,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk13": {
        "hk13_vorlauf_isttemperatur": {
            "register": 31391,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk13_vorlauf_solltemperatur": {
            "register": 31392,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk13_raumtemperatur": {
            "register": 31393,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk13_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41396,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_vorlauf_temperatur_externe_vorgabe": {
            "register": 48013,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_pumpe_an_aus": {"coil": 1390, "type": "binary_sensor"},
        "hk13_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41392,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41393,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41400,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41394,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41397,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41398,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_frostschutztemperatur": {
            "register": 41399,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41406,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk13_betriebsart": {
            "register": 48059,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk13_freigabe_externe_vorgabe": {
            "register": 48041,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk14": {
        "hk14_vorlauf_isttemperatur": {
            "register": 31421,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk14_vorlauf_solltemperatur": {
            "register": 31422,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk14_raumtemperatur": {
            "register": 31423,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk14_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41426,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_vorlauf_temperatur_externe_vorgabe": {
            "register": 48014,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_pumpe_an_aus": {"coil": 1420, "type": "binary_sensor"},
        "hk14_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41422,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41423,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41430,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41424,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41427,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41428,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_frostschutztemperatur": {
            "register": 41429,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41436,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk14_betriebsart": {
            "register": 48060,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk14_freigabe_externe_vorgabe": {
            "register": 48042,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk15": {
        "hk15_vorlauf_isttemperatur": {
            "register": 31451,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk15_vorlauf_solltemperatur": {
            "register": 31452,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk15_raumtemperatur": {
            "register": 31453,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk15_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41456,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_vorlauf_temperatur_externe_vorgabe": {
            "register": 48015,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_pumpe_an_aus": {"coil": 1450, "type": "binary_sensor"},
        "hk15_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41452,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41453,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41460,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41454,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41457,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41458,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_frostschutztemperatur": {
            "register": 41459,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41466,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk15_betriebsart": {
            "register": 48061,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk15_freigabe_externe_vorgabe": {
            "register": 48043,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk16": {
        "hk16_vorlauf_isttemperatur": {
            "register": 31481,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk16_vorlauf_solltemperatur": {
            "register": 31482,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk16_raumtemperatur": {
            "register": 31483,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk16_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41486,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_vorlauf_temperatur_externe_vorgabe": {
            "register": 48016,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_pumpe_an_aus": {"coil": 1480, "type": "binary_sensor"},
        "hk16_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41482,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41483,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41490,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41484,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41487,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41488,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_frostschutztemperatur": {
            "register": 41489,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41496,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk16_betriebsart": {
            "register": 48062,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk16_freigabe_externe_vorgabe": {
            "register": 48044,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk17": {
        "hk17_vorlauf_isttemperatur": {
            "register": 31511,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk17_vorlauf_solltemperatur": {
            "register": 31512,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk17_raumtemperatur": {
            "register": 31513,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk17_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41516,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_vorlauf_temperatur_externe_vorgabe": {
            "register": 48017,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_pumpe_an_aus": {"coil": 1510, "type": "binary_sensor"},
        "hk17_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41512,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41513,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41520,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41514,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41517,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41518,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_frostschutztemperatur": {
            "register": 41519,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41526,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk17_betriebsart": {
            "register": 48063,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk17_freigabe_externe_vorgabe": {
            "register": 48045,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "hk18": {
        "hk18_vorlauf_isttemperatur": {
            "register": 31541,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "hk18_vorlauf_solltemperatur": {
            "register": 31542,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk18_raumtemperatur": {
            "register": 31543,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "type": "sensor",
        },
        "hk18_gewuenschte_raumtemperatur_heizbetrieb": {
            "register": 41546,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_vorlauf_temperatur_externe_vorgabe": {
            "register": 48018,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 75,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_pumpe_an_aus": {"coil": 1540, "type": "binary_sensor"},
        "hk18_vorlauf_temperatur_10c_aussentemperatur": {
            "register": 41542,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_vorlauf_temperatur_minus_10c_aussentemperatur": {
            "register": 41543,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 110,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_heizkreispumpe_ausschalten_wenn_vorlauf_soll_kleiner_ist_als": {
            "register": 41550,
            "unit": "°C",
            "scaling": 2,
            "min": 10,
            "max": 30,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_absenkung_der_vorlauftemperatur_im_absenkbetrieb": {
            "register": 41544,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 70,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_aussentemperatur_unter_der_die_heizkreispumpe_im_heizbetrieb_einschaltet": {
            "register": 41547,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_aussentemperatur_unter_der_die_heizkreispumpe_im_absenkbetrieb_einschaltet": {
            "register": 41548,
            "unit": "°C",
            "scaling": 2,
            "min": -20,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_frostschutztemperatur": {
            "register": 41549,
            "unit": "°C",
            "scaling": 2,
            "min": -10,
            "max": 20,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_temp_am_puffer_oben_ab_der_der_ueberhitzungsschutz_aktiv_wird": {
            "register": 41556,
            "unit": "°C",
            "scaling": 1,
            "min": 60,
            "max": 120,
            "type": "number",
            "device_class": "temperature",
        },
        "hk18_betriebsart": {
            "register": 48064,
            "options": [
                "aus",
                "automatik",
                "extraheizen",
                "absenken",
                "dauerabsenken",
                "partybetrieb",
            ],
            "min": 0,
            "max": 5,
            "type": "select",
        },
        "hk18_freigabe_externe_vorgabe": {
            "register": 48046,
            "options": [
                "aus",
                "ein",
            ],
            "min": 0,
            "max": 1,
            "type": "select",
        },
    },
    "austragung": {
        "fuellstand_im_pelletsbehaelter": {
            "register": 30022,
            "unit": "%",
            "scaling": 207,
            "decimals": 1,
            "type": "sensor",
        },
        "resetierbarer_kg_zaehler": {
            "register": 30082,
            "unit": "kg",
            "scaling": 1,
            "device_class": "weight",
            "type": "sensor",
        },
        "resetierbarer_t_zaehler": {
            "register": 30083,
            "unit": "t",
            "scaling": 1,
            "device_class": "weight",
            "type": "sensor",
        },
        "pelletverbrauch_gesamt": {
            "register": 30084,
            "unit": "t",
            "scaling": 10,
            "decimals": 1,
            "device_class": "weight",
            "state_class": "total",
            "type": "sensor",
        },
        "pelletlager_restbestand": {
            "register": 40320,
            "unit": "t",
            "scaling": 10,
            "decimals": 1,
            "min": 0,
            "max": 100,
            "type": "number",
        },
    },
    "puffer01": {
        "puffer_1_temperatur_oben": {
            "register": 32001,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_mitte": {
            "register": 32002,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_unten": {
            "register": 32003,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_fuehler_2": {
            "register": 32005,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_temperatur_fuehler_3": {
            "register": 32006,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_1_pufferpumpen_ansteuerung": {
            "register": 32004,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "puffer_1_ladezustand": {
            "register": 32007,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_1_pufferpumpe_an_aus": {
            "register": 32004,
            "type": "binary_sensor_from_register",
        },
    },
    "puffer02": {
        "puffer_2_temperatur_oben": {
            "register": 32041,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_2_temperatur_mitte": {
            "register": 32042,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_2_temperatur_unten": {
            "register": 32043,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_2_pufferpumpen_ansteuerung": {
            "register": 32044,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "puffer_2_ladezustand": {
            "register": 32045,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_2_pufferpumpe_an_aus": {
            "register": 32044,
            "type": "binary_sensor_from_register",
        },
    },
    "puffer03": {
        "puffer_3_temperatur_oben": {
            "register": 32081,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_3_temperatur_mitte": {
            "register": 32082,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_3_temperatur_unten": {
            "register": 32083,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_3_pufferpumpen_ansteuerung": {
            "register": 32084,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "puffer_3_ladezustand": {
            "register": 32045,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_3_pufferpumpe_an_aus": {
            "register": 32084,
            "type": "binary_sensor_from_register",
        },
    },
    "puffer04": {
        "puffer_4_temperatur_oben": {
            "register": 32121,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_4_temperatur_mitte": {
            "register": 32122,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_4_temperatur_unten": {
            "register": 32123,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "puffer_4_pufferpumpen_ansteuerung": {
            "register": 32124,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "puffer_4_ladezustand": {
            "register": 32125,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "puffer_4_pufferpumpe_an_aus": {
            "register": 32124,
            "type": "binary_sensor_from_register",
        },
    },
    "zirkulationspumpe": {
        "ruecklauftemperatur_an_der_zirkulations_leitung": {
            "register": 30712,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "stoemungsschalter_an_der_brauchwasser_leitung": {
            "register": 30601,
            "unit": "",
            "scaling": 2,
            "type": "sensor",
        },
        "drehzahl_der_zirkulations_pumpe": {
            "register": 30711,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "zirkulationspumpe_an_aus": {
            "register": 30711,
            "type": "binary_sensor_from_register",
        },
    },
    "zweitkessel": {
        "start_zweitkessel": {
            "register": 40504,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "register_type": "holding",
        },
        "rueckschaltverzoegerung_zweitkessel_umschaltventil": {
            "register": 40512,
            "unit": "s",
            "scaling": 1,
            "register_type": "holding",
        },
        "temperatur_zweitkessel": {
            "register": 30501,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "umschaltventil_zweitkessel": {
            "register": 30504,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
        },
        "zustand_brennerrelais": {
            "register": 30502,
            "unit": "",
            "scaling": 1,
            "type": "sensor",
        },
        "betriebsstunden_zweitkessel": {
            "register": 30503,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "minimaltemperatur_zweitkessel": {
            "register": 40507,
            "unit": "°C",
            "scaling": 2,
            "min": 20,
            "max": 95,
            "type": "number",
            "device_class": "temperature",
        },
        "temperaturdifferenz_zweitkessel_puffer": {
            "register": 40508,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "minimale_laufzeit_zweitkessel": {
            "register": 40505,
            "unit": "min",
            "scaling": 60,
            "min": 0,
            "max": 500,
            "type": "number",
        },
        "einschaltverzoegerung_zweitkessel": {
            "register": 40502,
            "unit": "min",
            "scaling": 60,
            "min": 0,
            "max": 500,
            "type": "number",
        },
    },
    "solarthermie": {
        "kollektor_ruecklauftemperatur": {
            "register": 32612,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "kollektor_vorlauftemperatur": {
            "register": 32613,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "kollektortemperatur": {
            "register": 32602,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "solarfuehler_puffer_oben": {
            "register": 32008,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "solarfuehler_puffer_unten": {
            "register": 30029,
            "unit": "°C",
            "scaling": 2,
            "device_class": "temperature",
            "state_class": "measurement",
            "type": "sensor",
        },
        "laufzeit_kollektorpumpe": {
            "register": 32603,
            "unit": "h",
            "scaling": 1,
            "type": "sensor",
        },
        "aktuelle_leistung_des_solar_wmz": {
            "register": 32611,
            "unit": "kW",
            "scaling": 100,
            "decimals": 2,
            "device_class": "power",
            "type": "sensor",
        },
        "ansteuerung_kollektorpumpe": {
            "register": 32601,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "aktuelle_ansteuerung_der_kollektor_boiler_pumpe": {
            "register": 32623,
            "unit": "%",
            "scaling": 1,
            "type": "sensor",
            "device_class": "power_factor",
        },
        "solarthermie_dfl_sensor": {
            "register": 32610,
            "unit": "L/h",
            "scaling": 1,
            "device_class": "volume_flow_rate",
            "type": "sensor",
        },
        "solarthermie_tagesertrag": {
            "register": 32620,
            "unit": "kWh",
            "scaling": 1,
            "device_class": "energy",
            "type": "sensor",
        },
        "solarthermie_gesamtertrag": {
            "register": 32622,
            "unit": "kWh",
            "scaling": 1,
            "device_class": "energy",
            "state_class": "total",
            "type": "sensor",
        },
        "maximale_puffertemperatur_unten_bei_solarladung": {
            "register": 42603,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 90,
            "type": "number",
            "device_class": "temperature",
        },
        "kollektor_einschalt_differenz": {
            "register": 42601,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
        "kollektor_ausschalt_differenz": {
            "register": 42602,
            "unit": "°C",
            "scaling": 2,
            "min": 0,
            "max": 50,
            "type": "number",
            "device_class": "temperature",
        },
    },
}
from .custom_entity_definitions import apply_custom_entity_definitions

apply_custom_entity_definitions(ENTITY_DEFINITIONS)